FROM node:10.15.0-alpine as build

RUN mkdir /client

WORKDIR ./client

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# nginx

FROM nginx:1.16.0-alpine as production

RUN mkdir -p /var/www/html/

COPY --from=build /client/build /var/www/html/

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./nginx.vh.default.conf /etc/nginx/nginx.vh.default.conf

STOPSIGNAL SIGTERM

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
