const images = {
  phone: require('../images/phone.png'),
  logo: require('../images/logo.png'),
  colorLogo: require('../images/logo-color.jpg'),
  facebook: require('../images/facebook.png'),
  google: require('../images/google.png'),
  twitter: require('../images/twitter.png'),
  envelope: require('../images/email-outline.png'),
  companyNamesBlue: require('../images/cards/Company-Names_blue.png'),
  companyNamesGrey: require('../images/cards/Company-Names_grey.png'),
  logosBlue: require('../images/cards/Logos_blue.png'),
  logosGrey: require('../images/cards/Logos_grey.png'),
  taglinesBlue: require('../images/cards/Taglines_blue.png'),
  taglineGrey: require('../images/cards/Taglines_grey.png'),
  checkBox: require('../images/check-box-outline.png'),
  briefcase: require('../images/briefcase-account-outline.png'),
  square: require('../images/checkbox-blank-outline.png'),
  bookmark: require('../images/bookmark-outline.svg'),
  heart: require('../images/heart-outline.svg'),
  package: require('../images/package.svg'),
  telegramTop: require('../images/telegramTop.svg'),
  dots: require('../images/dots.svg'),
  arrow: require('../images/arrow-left.svg'),
  community: require('../images/more-benifits-world-icon.png'),
  quality: require('../images/more-benifits-high-quality-icon.png'),
  trademark: require('../images/more-benifits-trademark-icon.png'),
  mashable: require('../images/mashable.png'),
  chicago: require('../images/chicago.png'),
  forbes: require('../images/forbes-logo-vectorbw.png'),
  web: require('../images/the_next_webbw.png'),
  step1: require('../images/1-compressed.gif'),
  step2: require('../images/2-compressed-new.gif'),
  step3: require('../images/3-compressed.gif'),
  cash: require('../images/start-contest-cash.png'),
  satisfaction: require('../images/start-contest-satisfaction.png'),
  send: require('../images/telegram.png'),
  flask: require('../images/flask-outline.png'),
  oneTick: require('../images/one_tick.png'),
  doubleTick: require('../images/double-tick.png'),

  redWind: require('../images/slider/21..jpg'),
  pepperSt: require('../images/slider/B_1_01.jpg'),
  quantic: require('../images/slider/Banner_Visual_Name_W_33_Quantic.jpg'),
  forwardFocused: require('../images/slider/Banner_Visual_Name_AB_20_ForwardFocused.jpg'),
  avanti: require('../images/slider/Banner_Visual_Name_P_42_Avanti.jpg'),
  onpoint: require('../images/slider/VisualNames_onpoint.jpg'),
  analytIQ: require('../images/slider/Banner_Visual_Name_Z_19_AnalytIQ.jpg'),
  infamiss: require('../images/slider/B_2_15.jpg'),
  pawxie: require('../images/slider/Banner_Visual_Name_AK_03_pawxie.jpg'),
  styleRevolver: require('../images/slider/Banner_Visual_Name_AA_48_StyleRevolver.jpg'),

  exactly: require('../images/slider/8641707.jpg'),
  upzin: require('../images/slider/10225472.jpg'),
  galore: require('../images/slider/8692455.jpg'),
  luckSt: require('../images/slider/9258858.jpg'),
  ready: require('../images/slider/9085138.jpg'),
  impurest: require('../images/slider/10867491.jpg'),
  avatar2: require('../images/slider/IMG_9074-avatar.jpg'),
  avatar3: require('../images/slider/Unbenannt1-avatar.jpg'),
};

export default images;
